name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0/6 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: true
          SYMBOL_VERSION: '3'
          SHOW_LANGUAGE: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_SHORT_INFO: true
          SHOW_LANGUAGE_PER_REPO: true
          
          
